[package]
name = "scarlet"
description = "Colors and color spaces made simple"
version = "0.1.1"
authors = ["Nicholas Miklaucic <nicholas.miklaucic@gmail.com>"]
license = "Apache-2.0"
readme = "README.MD"
repository = "https://github.com/nicholas-miklaucic/scarlet"
keywords = ["color", "rgb", "image", "visualization"]
categories = ["multimedia::images", "visualization", "data-structures"]


[dependencies]
regex = "0.2"
termion = "1"
num = "0.1.41"
float-cmp = "0.4.0"
csv = "1.0.0-beta.5"
serde = "1"
serde_derive = "1"
geo = "0.7.1"
nalgebra = "0.14"
maplit = "1.0.1"
lazy_static = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-after-content colorize.html"]